# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/Время публикации')),
                ('article_image', models.ImageField(upload_to='art_image', verbose_name='Изображение для статьи')),
                ('is_private', models.BooleanField(default=True, verbose_name='Скрытая статья')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Статья',
                'db_table': 'Articles',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-article_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'db_table': 'Categories',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='my_blog.Categories', verbose_name='Категория'),
        ),
    ]
