# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, unique=True, verbose_name='Article title')),
                ('article_text', models.TextField(verbose_name='Article text')),
                ('article_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/time publishing')),
                ('article_image', models.ImageField(blank=True, default='', null=True, upload_to='art_image', verbose_name='Image article')),
                ('is_private', models.BooleanField(default=True, verbose_name='Private article')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Article',
                'db_table': 'Articles',
                'verbose_name_plural': 'Articles',
                'ordering': ['-article_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'Categories',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='my_blog.Categories', verbose_name='Category'),
        ),
    ]
