# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-03 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_letters', models.BooleanField(default=True, verbose_name='Uppercase letters')),
                ('low_letters', models.BooleanField(default=True, verbose_name='Lowercase letters')),
                ('digits', models.BooleanField(default=False, verbose_name='Digital symbols')),
                ('spec_symbols', models.BooleanField(default=False, verbose_name='Special symbols')),
                ('length', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Password length')),
            ],
            options={
                'verbose_name_plural': 'Generators',
                'verbose_name': 'Generator',
            },
        ),
    ]
