# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-26 20:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_generator', '0003_auto_20170919_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generator',
            options={'verbose_name': 'Генератор строки', 'verbose_name_plural': 'Генераторы строк'},
        ),
        migrations.AlterField(
            model_name='generator',
            name='digits',
            field=models.BooleanField(default=False, help_text='0-9', verbose_name='Цифры'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='length',
            field=models.PositiveIntegerField(default=8, help_text='Длинна должна быть от 1 до 100 символов', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Длинна пароля'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='low_letters',
            field=models.BooleanField(default=True, help_text='a-z', verbose_name='Строчные буквы'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='number',
            field=models.PositiveIntegerField(default=10, help_text='Длинна должна быть от 1 до 100 символов', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Количество паролей'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='spec_symbols',
            field=models.BooleanField(default=False, help_text='!#$%&()*+,-./:;<=>?@[\\]^_`{|}~', verbose_name='Специальные символы'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='up_letters',
            field=models.BooleanField(default=True, help_text='A-Z', verbose_name='Заглавные буквы'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='user_symbols',
            field=models.CharField(blank=True, default='', help_text='100 символов максимум', max_length=100, null=True, verbose_name='Пользовательские символы'),
        ),
    ]
