# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-19 17:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dif_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='user_symbols',
            field=models.CharField(default='', max_length=100, verbose_name='User input symbols'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='digits',
            field=models.BooleanField(default=False, help_text='0-9', verbose_name='Digital symbols'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='length',
            field=models.PositiveIntegerField(default=8, help_text='The length must be from 1 to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Password length'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='low_letters',
            field=models.BooleanField(default=True, help_text='a-z', verbose_name='Lowercase letters'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='spec_symbols',
            field=models.BooleanField(default=False, help_text='!#$%&*()/<>', verbose_name='Special symbols'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='up_letters',
            field=models.BooleanField(default=True, help_text='A-Z', verbose_name='Uppercase letters'),
        ),
    ]
