# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-19 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dif_apps', '0002_auto_20170919_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='number',
            field=models.PositiveIntegerField(default=10, help_text='The length must be from 1 to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Number of passwords'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='user_symbols',
            field=models.CharField(blank=True, default='', help_text='100 symbols max', max_length=100, null=True, verbose_name='User input symbols'),
        ),
    ]
