# Generated by Django 2.1.5 on 2019-01-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dif_apps', '0004_auto_20180226_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generator',
        ),
    ]
